### PR TITLE
Mass renaming mess + ragdoll fix

### PR DESCRIPTION
**Pull request by SpiderBuh**
My hyperfocus mess that is the half commented out mass-renaming thing, and 2 lines that should prevent errors when calling the ragdoll command on a dead player

### CODE REVIEW

**Comment by ThePheggHerself** [comment]
Why is half of it commented out? xD

**Comment by SpiderBuh** [comment]
It kept freezing the server and I have no idea why

**Comment by ThePheggHerself** [comment]
It doesn't appear to crash on the main test server, possibly something related to your server being run via Pterodactyl (You should have access. If not, lmk)

**Comment by SpiderBuh** [comment]
> It kept freezing the server and I have no idea why

Ok I SWEAR it used to be a for loop and not a while loop guys

**Pull request merged**
